"""/api/colab — turn a reproduce snippet into a one-click Colab notebook.

Colab can't accept inline code via URL, so we create a public GitHub gist containing a
real .ipynb and return its Colab URL (https://colab.research.google.com/gist/<id>). The
notebook is fully parameterized to the user's exact query — open it and Run All to verify.

POST { code: "<python>", title?: "..." } -> { colab_url }
Needs env GH_GIST_TOKEN (a GitHub token with gist scope).
"""
import json
import os
import urllib.request
from http.server import BaseHTTPRequestHandler


def make_notebook(code, title="Reproduce — USAspending Table Builder"):
    return {
        "cells": [
            {"cell_type": "markdown", "metadata": {},
             "source": [f"# {title}\n", "Generated by the USAspending Table Builder. ",
                        "Run all cells to reproduce the result from the public dataset."]},
            {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [],
             "source": code.splitlines(keepends=True)},
        ],
        "metadata": {"kernelspec": {"name": "python3", "display_name": "Python 3"},
                     "language_info": {"name": "python"}},
        "nbformat": 4, "nbformat_minor": 5,
    }


def make_colab(code, title=None):
    token = os.environ["GH_GIST_TOKEN"]
    nb = make_notebook(code, title or "Reproduce — USAspending Table Builder")
    body = json.dumps({
        "description": "USAspending Table Builder — reproducible query",
        "public": True,
        "files": {"reproduce.ipynb": {"content": json.dumps(nb, indent=1)}},
    }).encode()
    req = urllib.request.Request(
        "https://api.github.com/gists", data=body, method="POST",
        headers={"Authorization": f"Bearer {token}",
                 "Accept": "application/vnd.github+json",
                 "User-Agent": "usaspending-table-builder"})
    gist = json.loads(urllib.request.urlopen(req, timeout=30).read())
    # Colab needs the owner in the path: /gist/<user>/<id>/<filename>
    return (f"https://colab.research.google.com/gist/{gist['owner']['login']}/"
            f"{gist['id']}/reproduce.ipynb")


class handler(BaseHTTPRequestHandler):
    def _send(self, code, body):
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(json.dumps(body).encode())

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_POST(self):
        try:
            n = int(self.headers.get("Content-Length", 0))
            payload = json.loads(self.rfile.read(n) or b"{}")
            self._send(200, {"colab_url": make_colab(payload["code"], payload.get("title"))})
        except Exception as e:
            self._send(400, {"error": str(e)})
